cloud:
  aws:
    credentials:
      access-key: { access-key }
      secret-key: { aws-secret-key }
    region:
      static: us-east-1
    stack:
      auto: false

application:
  bucket:
    name: javas3demoapp

spring:
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2MB
      max-file-size: 5MB
      max-request-size: 10MB


server:
  port: 9090